name: Hampa CBD
favicon: null
layout_spectrum: 0.6658171084709466
typography_spectrum: 0.3774443664588034
title: Hampa olja en hälsåsamt tradition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afafad'
    - '#395144'
    - '#5e7f6e'
    - '#231f20'
    - '#d6dbde'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.7972960351034999
purpose: []
