name: Hampa CBD
favicon: null
layout_spectrum: 0.6658171084709466
typography_spectrum: 0.3774443664588034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0000'
    - '#fdd9cd'
    - '#513000'
    - '#df9d83'
    - '#b1803c'
  brandStrength: 0.1724632796831429
  lightness: 0.37242663046345115
  saturation: 0.3018586868420243
  rhythmicContrast: 0.7972960351034999
purpose: []
